// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./components/App.vue')['default']
    DropDown: typeof import('./components/ui/dropdown/DropDown.vue')['default']
    FlagEN: typeof import('./components/ui/flags/FlagEN.vue')['default']
    FlagRU: typeof import('./components/ui/flags/FlagRU.vue')['default']
    FooterBlock: typeof import('./components/ui/layouts/BigComponents/FooterBlock.vue')['default']
    LangSwitcher: typeof import('./components/ui/layouts/SmallComponents/LangSwitcher.vue')['default']
    NavbarBlock: typeof import('./components/ui/layouts/BigComponents/NavbarBlock.vue')['default']
    PostBody: typeof import('./components/views/posts/PostsDisplay/PostFullDisplay/PostBody.vue')['default']
    PostFull: typeof import('./components/views/posts/PostsDisplay/PostFull.vue')['default']
    PostHeader: typeof import('./components/views/posts/PostsDisplay/PostFullDisplay/PostHeader.vue')['default']
    PostHeaderField: typeof import('./components/views/posts/PostsDisplay/PostFullDisplay/PostHeaderField.vue')['default']
    PostsAll: typeof import('./components/views/posts/PostsAll.vue')['default']
    PostsByCategory: typeof import('./components/views/posts/PostsByCategory.vue')['default']
    PostShort: typeof import('./components/views/posts/PostsDisplay/PostShort.vue')['default']
    PostShortType01: typeof import('./components/views/posts/PostsDisplay/PostShortTypes/PostShortType01.vue')['default']
    PostShortType02: typeof import('./components/views/posts/PostsDisplay/PostShortTypes/PostShortType02.vue')['default']
    PostShortType03: typeof import('./components/views/posts/PostsDisplay/PostShortTypes/PostShortType03.vue')['default']
    PostShortType04: typeof import('./components/views/posts/PostsDisplay/PostShortTypes/PostShortType04.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinnerLoader: typeof import('./components/ui/layouts/SmallComponents/SpinnerLoader.vue')['default']
    TabSingle: typeof import('./components/ui/tabs/TabSingle.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TeamAll: typeof import('./components/views/team/TeamAll.vue')['default']
    TeamFull: typeof import('./components/views/team/TeamDisplay/TeamFull.vue')['default']
    TeamShort: typeof import('./components/views/team/TeamDisplay/TeamShort.vue')['default']
  }
}
